services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=erp_database'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=application'
    ports:
      - '5432'
